using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI; // Nutné pro práci s UI komponentami

public class CudlikZmenaSceny : MonoBehaviour
{
    // Toto políčko uvidíš v Inspectoru přímo u tlačítka
    [SerializeField] private string nazevCiloveSceny;

    void Start()
    {
        // Automaticky řekne tlačítku, co má dělat, když na něj klikneš
        Button btn = GetComponent<Button>();
        if (btn != null)
        {
            btn.onClick.AddListener(Prejdi);
        }
    }

    void Prejdi()
    {
        if (!string.IsNullOrEmpty(nazevCiloveSceny))
        {
            SceneManager.LoadScene(nazevCiloveSceny);
        }
        else
        {
            Debug.LogWarning("Zapomněl jsi vyplnit název scény na objektu: " + gameObject.name);
        }
    }
}